### PR TITLE
fix: security vulnerability for mac, linux and windows

### PR DESCRIPTION
**Pull request by SteinRobert**
Fixes CLI command injection vulnerability.  The fix currently only contains changes for MacOS and Linux. If you think it's looking good I can help make the adaptions for Windows as well.

## Motivation and Context

Make the package more safe to be installed and use.

## Usage examples

```
wifi --connect --ssid <ssid> --password <password>
```

## How Has This Been Tested?

Manual tests on Linux and MacOS.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Security Fix

### CODE REVIEW

**Comment by friedrith** [comment]
Your code seems me very clear. I thinkt it would be nice to do it for windows too. Besides, you should fix prettier issue. You can do it using command `npm run prettier:fix`

**Comment by SteinRobert** [comment]
@friedrith just updated the branch with the adaptions for Windows and the fixes for prettier.
Besides - I also just tested the adaptions for Windows - everything went well, except you should probably merge this PR: https://github.com/friedrith/node-wifi/pull/80
The adaption is necessary to connect to a wifi on Windows.

**Comment by friedrith** [comment]
Oups thank you for the reminder for #80 I totally forgot to merge it. But unfortunately when I merged #80, conflicts happened with your pull request. Can you update it ? 

I appreciate a lot your work and your effort. Thx !

**Comment by SteinRobert** [comment]
Just updated the branch. 😄

**Comment by friedrith** [comment]
Great let's merge it !

**Comment by friedrith** [comment]
It will be integrated in next release that should be published today or tomorrow.

**Comment by friedrith** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
