### PR TITLE
Refactor using lebab

### PR DESCRIPTION
**Pull request by jimmywarting**
## Description
No manual changes was made... (less cause of failure)

Executed 
- `lebab --replace ./ --transform arrow,let,includes,template,default-param,obj-shorthand,obj-method,arg-spread,arg-rest,for-each,class`
- `standard --fix`
- `npm run format:fix`
- `npm run lint`
- `npm run test`

## Motivation and Context

modernize

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactorization (non-functional change which improve code readibility)

### CODE REVIEW

**Comment by friedrith** [comment]
Ok I look into that this weekend. 👍

**Comment by jimmywarting** [comment]
friendly ping

**Comment by friedrith** [comment]
> friendly ping

Merged ;)

**Comment by jimmywarting** [comment]
> Merged ;)

thx

**Comment by friedrith** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
