### PR TITLE
Wait until device is connected, delete profile if connection fails

### PR DESCRIPTION
**Pull request by paumoreno**
We are using this library in Windows, and we detected that `connectToWifi`'s callback is called when Windows is told to connect to the network instead of waiting for it to actually connect.

I changed its behaviour, so it waits until `netsh wlan connect` is done and the profile XML is deleted.

Additionally, if the connection fails, the function also takes care of deleting the created connection profile.

### CODE REVIEW

**Comment by paumoreno** [comment]
Fixes #25

**Comment by friedrith** [comment]
You are totally right. I am just waiting to release the 2.0 version of node-wifi before accepting your pull request. It will be ok this weekend I think.

**Comment by friedrith** [comment]
There is a conflict after releasing version 2.0

**Comment by paumoreno** [comment]
Rewritten and tested!

**Comment by paumoreno** [comment]
Sorry, I added a new functionality in the same dev branch, which is related to issue #30

**Comment by friedrith** [comment]
Thx for all your contribution. I check it this weekend on my own and I accept it just after.

**Comment by friedrith** [comment]
I have read your PL and thank you a lot. It is quite clear. You added scan before connection in order to get the wifi network security protocol. So by this way you can connect to WEP.

Moreover, you used promises to better manager workflow and catch errors. I was not very happy to use promise because of Javascript compatibilities (Older versions of node don't manage promise I think) but whatever !

**Pull request merged**
