### PR TITLE
Export `qualityFromDB` in `src/network-utils.js`

### PR DESCRIPTION
**Pull request by kirbo**
I was getting an error `networkUtils.qualityFromDB is not a function` or something, in here [`node_modules/node-wifi/src/mac-current-connections.js:14:47`](https://github.com/friedrith/node-wifi/blob/master/src/mac-current-connections.js#L14), so I added it into exports -> now I'm not getting the same error anymore.

### CODE REVIEW

**Comment by MartinsYong** [comment]
From issue [#65](https://github.com/friedrith/node-wifi/issues/65)

**Comment by kirbo** [comment]
Any plans to merge this? I'd like to use your package/repo instead of the one I have in my other project...

**Comment by liveKang** [comment]
please merge request, thx.

**Comment by friedrith** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
